// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ExcerciseOne.WebApp.Services.WebApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ApiParking
    {
        /// <summary>
        /// Initializes a new instance of the ApiParking class.
        /// </summary>
        public ApiParking() { }

        /// <summary>
        /// Initializes a new instance of the ApiParking class.
        /// </summary>
        public ApiParking(int? id = default(int?), int? parkingId = default(int?), string name = default(string), double? latitude = default(double?), double? longitude = default(double?))
        {
            Id = id;
            ParkingId = parkingId;
            Name = name;
            Latitude = latitude;
            Longitude = longitude;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ParkingId")]
        public int? ParkingId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Latitude")]
        public double? Latitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Longitude")]
        public double? Longitude { get; set; }

    }
}
