// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ExcerciseOne.WebApp.Services.WebApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ApiRoute
    {
        /// <summary>
        /// Initializes a new instance of the ApiRoute class.
        /// </summary>
        public ApiRoute() { }

        /// <summary>
        /// Initializes a new instance of the ApiRoute class.
        /// </summary>
        public ApiRoute(int? id = default(int?), int? routeId = default(int?), int? vehicleId = default(int?), int? departureId = default(int?), int? destinationId = default(int?))
        {
            Id = id;
            RouteId = routeId;
            VehicleId = vehicleId;
            DepartureId = departureId;
            DestinationId = destinationId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RouteId")]
        public int? RouteId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VehicleId")]
        public int? VehicleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DepartureId")]
        public int? DepartureId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DestinationId")]
        public int? DestinationId { get; set; }

    }
}
