// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ExcerciseOne.WebApp.Services.WebApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ApiSummary
    {
        /// <summary>
        /// Initializes a new instance of the ApiSummary class.
        /// </summary>
        public ApiSummary() { }

        /// <summary>
        /// Initializes a new instance of the ApiSummary class.
        /// </summary>
        public ApiSummary(int? id = default(int?), int? routeId = default(int?), string vehicle = default(string), double? enterCost = default(double?), double? distanceCost = default(double?), string depName = default(string), double? depLatitude = default(double?), double? depLongitude = default(double?), string desName = default(string), double? desLatitude = default(double?), double? desLongitude = default(double?))
        {
            Id = id;
            RouteId = routeId;
            Vehicle = vehicle;
            EnterCost = enterCost;
            DistanceCost = distanceCost;
            DepName = depName;
            DepLatitude = depLatitude;
            DepLongitude = depLongitude;
            DesName = desName;
            DesLatitude = desLatitude;
            DesLongitude = desLongitude;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RouteId")]
        public int? RouteId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Vehicle")]
        public string Vehicle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EnterCost")]
        public double? EnterCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DistanceCost")]
        public double? DistanceCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DepName")]
        public string DepName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DepLatitude")]
        public double? DepLatitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DepLongitude")]
        public double? DepLongitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DesName")]
        public string DesName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DesLatitude")]
        public double? DesLatitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DesLongitude")]
        public double? DesLongitude { get; set; }

    }
}
