// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ExcerciseOne.WebApp.Services.WebApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ApiVehicle
    {
        /// <summary>
        /// Initializes a new instance of the ApiVehicle class.
        /// </summary>
        public ApiVehicle() { }

        /// <summary>
        /// Initializes a new instance of the ApiVehicle class.
        /// </summary>
        public ApiVehicle(int? id = default(int?), int? vehicleId = default(int?), string name = default(string), double? enterCost = default(double?), double? distanceCost = default(double?))
        {
            Id = id;
            VehicleId = vehicleId;
            Name = name;
            EnterCost = enterCost;
            DistanceCost = distanceCost;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VehicleId")]
        public int? VehicleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EnterCost")]
        public double? EnterCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DistanceCost")]
        public double? DistanceCost { get; set; }

    }
}
