//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcerciseOne.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRoute
    {
        public int Id { get; set; }
        public int RouteId { get; set; }
        public int DepartureId { get; set; }
        public int DestinationId { get; set; }
        public int VehicleId { get; set; }
    
        public virtual TblParking TblParking { get; set; }
        public virtual TblParking TblParking1 { get; set; }
        public virtual TblVehicle TblVehicle { get; set; }
    }
}
