//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcerciseOne.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VieSummary
    {
        public int Id { get; set; }
        public int RouteId { get; set; }
        public string Vehicle { get; set; }
        public Nullable<decimal> EnterCost { get; set; }
        public Nullable<decimal> DistanceCost { get; set; }
        public string DepName { get; set; }
        public Nullable<decimal> DepLatitude { get; set; }
        public Nullable<decimal> DepLongitude { get; set; }
        public string DesName { get; set; }
        public Nullable<decimal> DesLatitude { get; set; }
        public Nullable<decimal> DesLongitude { get; set; }
    }
}
